project_structure:
    build: tests/brownie/build
    contracts: tests/brownie/contracts
    interfaces: tests/brownie/interfaces
    reports: tests/brownie/reports
    scripts: tests/brownie/scripts
    tests: tests
compiler:
    solc:
        remappings:
          - "@uniswap=tests/brownie/contracts/uniswap"